### ISSUE TITLE
Add support for --release-name-template flag

### ISSUE THREAD

**Issue by stevehipwell** [helm/chart-releaser-action#37]
It would be really useful for the `--release-name-template` flag to be supported via the action. It might even be worth supporting flags in a generic way so new flags don't need changes to the action code.

https://github.com/helm/chart-releaser/pull/74

**Comment by scottrigby** [comment]
Hey 👋 yes! Once we cut a new release for helm/chart-released someone will add the new configs to this action... Stay tuned!

**Comment by isaaguilar** [comment]
When the new helm/chart-releaser get released, wouldn't `env.CR_RELEASE_NAME_TEMPLATE` be a way to use that flag in the `cr upload` command?

**Comment by stevehipwell** [comment]
@scottrigby any news?

**Comment by cep21** [comment]
Hi,

My use case here is that I would like to put the chart in the same repository as the application itself.  Using this action becomes confusing for consumers of my product since they see a new github release of the name "product-1.2" when I'm really just changing the chart.  To resolve this, I would like to release the product itself as "product-1.2" and the chart for the product as "chart-product-x.y" so people are clear that the helm chart itself changed versions, but the product itself did not.

Thanks!

**Comment by llamahunter** [comment]
What's the status on this? I think many helm chart maintainers are going through pain right now because they are moving charts out of the helm stable/incubating repo and having trouble with chart naming in the process. Really need a way to control the release name to avoid collisions.

**Comment by stevehipwell** [comment]
I think this can be closed now thanks to [v1.1.0](https://github.com/helm/chart-releaser-action/releases/tag/v1.1.0)? It looks like setting the env variable `CR_RELEASE_NAME_TEMPLATE` should work.

**Comment by scottrigby** [comment]
@stevehipwell You're correct! Closing
